
## load relevant functions
source("R/cronbachs_alpha.R")


#' get the 'clean' sample correlation matrix from Johnson (2005)
#' 
#' To compute this sample correlation matrix, we take out all observations that were flagged by either antonyms, personal-reliability, or CODERS (at the liberal level of 1%). We use our own calculations (based on default settings in the \pkg{careless} package) and not the data that Johnson (2005) provides for the former two indices. We calculate the sample correlation matrix based on the remaining "clean" sample and round it to 2 decimal points (rounding to 1  decimal point would lead to loss of positive semidefiniteness). See \code{application/10johnson2005_cormat-for-sim.R} for details. Importantly, the correlation matrix is based on reverse-coded responses (so that within-scale correlations are expected to be all positive)
johnson05_cormat <- function()
{
  # load the correlation matrix (sorted by facets)
  #load("application/results/johnson2005_cleancormat.Rdata") # the Rdata file below is just that
  load("R/johnson2005_cleancormat.Rdata")
  
  # get the original order of the items (as presented to participants)
  item_order_original <- order(key_order)
  
  # update the item names
  colnames(cormat_clean_posword) <- rownames(cormat_clean_posword) <- key_membership[key_order]
  
  return(
    list(cormat_posword = cormat_clean_posword,
         item_order_ordrerd = key_order,
         item_order_original = item_order_original,
         item_keys_original = key_membership,
         item_facets_original = facets_membership,
         reverse_coded_original = which(key_sign == "-"))
  )
}


#' load the response marginals, following the same strategy as in \code{johnson05_cormat()}
johnson05_marginals <- function()
{
  # load the clean data: generated by `application/10johnson2005_cormat-for-sim.R`
  load("R/johnson2005_cleandata.Rdata")

  # get the original order of the items (as presented to participants)
  item_order_original <- order(key_order)
  
  return(
    list(response_marginals = marginals,
         cormat_posword = cormat_clean_posword,
         item_order_ordrerd = key_order,
         item_order_original = item_order_original,
         item_keys_original = key_membership,
         item_facets_original = facets_membership,
         reverse_coded_original = which(key_sign == "-"))
  )
}


#' load the clean data, following the same strategy as in \code{johnson05_cormat()}
johnson05_cleandata <- function()
{
  # load the clean data: generated by `application/10johnson2005_cormat-for-sim.R`
  load("R/johnson2005_cleandata.Rdata")
  
  # load information on response marginals
  j05obj <- johnson05_marginals()
  
  # get indices of negatively keyed items 
  idx_neg_keyed <- j05obj$reverse_coded_original
  keys <- rep(1L, ncol(data_given_clean))
  keys[idx_neg_keyed] <- -1L
  
  # NOTE: responses are given in chronological order (and contain 0 for NA)
  return(list(data = data_given_clean, keys = keys, 
              idx_ordered = j05obj$item_order_ordrerd))
}


#' Generate data by subsampling from the cleaned data of johnson2005
#'
#' @param data_j05 clean data of jognson2005 as returned by the participants
#' @param sample indices that shall be sampled
#' @param n size of the subsample (only relevant if \code{sample = NULL})
#'
#' @return list containing the data and the keys of the items
generate_data_johnson05clean <- function(data_j05, sample = NULL, n = NULL) {

  if(is.null(sample))
  {
    stopifnot(!is.null(n))
    stopifnot(n <= nrow(data_j05))
    sample. <- sample.int(nrow(data_j05), size = n, replace = FALSE)
  } else{
    sample. <- sample
  }
  
  # subsample
  data_out <- data_j05[sample.,]
  
  # return data (not recoded, and in order they were given)
  return(list(data = data_out))
}


#' generate data based on the correlation and distribution in clean data of johnson (2005)
generate_data_johnson05marginals <- function(n)
{
  ## all of the following information is based on positively worded items that are reordered
  j05obj <- johnson05_marginals()
  item_probabilities <- j05obj$response_marginals
  Rho <- j05obj$cormat_posword
  num_likert <- ncol(item_probabilities)
  num_items <- nrow(item_probabilities)
  
  # compute Cronbach's alpha of the scales
  alpha <- cronbachs_alpha(Rho = Rho, item_probabilities = item_probabilities,
                           scale_size = 10, num_scales = 30)
  names(alpha) <- 
    unique(j05obj$item_facets_original[j05obj$item_order_ordrerd])
  
  
  # generate data
  temp <- simstudy::genData(n)
  data <- simstudy::genOrdCat(temp,
                              baseprobs = item_probabilities,
                              prefix = "item",
                              corMatrix = Rho)
  
  # drop id column and convert to matrix
  data <- as.matrix(data[, -1])
  data <- matrix(as.integer(data), nrow = n)
  
  # reshuffle items to the original order as presented by Johnson (2005)
  idx_original <- j05obj$item_order_original
  data <- data[,idx_original]
  colnames(data) <- j05obj$item_keys_original
  
  # get indices of negatively keyed items 
  idx_neg_keyed <- j05obj$reverse_coded_original
  
  # adjust for negatively keyed items
  data[, idx_neg_keyed] <- num_likert - data[, idx_neg_keyed] + 1
  keys <- rep(1L, num_items)
  keys[idx_neg_keyed] <- -1L
  
  # return data and keys as list
  list(data = data, cronbachs_alpha = alpha, keys = keys, 
       idx_ordered = j05obj$item_order_ordrerd)
}



# traits_drop is either NULL or in in c("A", "E", "N", "O", "C")
johnson2005_droptrait <- function(data, traits_drop = NULL)
{
  # traits 
  drop_allowed <- c("A", "E", "N", "O", "C")
  item_traits <- substr(colnames(data), start = 1, stop = 1)
  item_names <- colnames(data)
  
  if(is.null(traits_drop))
  {
    out <- list(data = data, 
                idx_kept = seq_len(ncol(data)),
                item_order_ordrerd = order(item_names))
  } else
  {
    stopifnot(all(traits_drop %in% drop_allowed))
    items_keep <- !(item_traits %in% traits_drop)
    out <- list(data = data[,items_keep], 
                idx_kept = which(items_keep),
                item_order_ordrerd = order(item_names[items_keep]))
  } # IF
  
  return(out)
} # FUN
